### ISSUE TITLE
Extracting path from node selection

### ISSUE THREAD

**Issue by jneveux** [wix/angular-tree-control#138]
Hi,

I'm looking for a way to extract the full path when a node is selected. The function on-selection="showSelected(node)" returns the current node. Is there a simple way to compute the selected node path without re-parsing the whole tree?

Thanks,

Jean

**Comment by m-e-conroy** [comment]
I'm looking for this too, calculating it every time is quite intense.  Need something like this to make removing a nested node easier.

**Comment by yoavaa** [comment]
the problem with this feature is that I have no idea how to expose it. 
It makes no sense to compute the full path everytime a selection happens just in order to pass it as a parameter to the on-selection event expression. I can make a function that is passed as a parameter, and if called returns the array of nodes in the path.

e.g. (using lodash)
on the tree element:
```
on-selection="onSelection(node, $path)"
```
and the event handler
```

function onSelection(node, path) {
  var nodesInPath = path();
  var pathAsString = _.reduce(nodesInPath, function(string, node) {
    return string + "/" + node.title;
   }, "");
}
```

However, I am afraid people will find this way to confusing to use.

**Comment by shaie** [comment]
I am looking to do the same too. At first I thought I can implement a buildPath(node, $parentNode), since on-selection and on-node-toggle pass $parentNode, but turns out $parentNode doesn't have a .$parentNode itself. So maybe if the tree control already knows the parentNode of a given node, it can either store that for all nodes, allowing us to reconstruct the full path? Or maybe use whatever logic it uses now to determine the parent node of a selected node, to give us a function like parent(node), and we'll reconstruct the path using it?

**Comment by yoavaa** [comment]
done. see the $path function  - 
http://wix.github.io/angular-tree-control/#events
and
http://wix.github.io/angular-tree-control/#labels-template

**Comment by shaie** [comment]
Great, I'll try it out soon. Thanks!
