### ISSUE TITLE
expanded nodes does not fire onNodeToggle

### ISSUE THREAD

**Issue by andrius-kulbis** [wix/angular-tree-control#155]
I am saving the expanded nodes into cookie and after refresh want to open the same exact nodes, that was saved in cookie (I load children nodes async onNodeToggle). But after page refresh when I populate my scope variable with expanded nodes from cookie, the first node shows that it is expanded but the on-node-toggle callback is not called.

**Comment by yoavaa** [comment]
I understand that the tree works as planned in your case? After you set the expandedNodes, all the nodes are expanded, you only miss the on-toggle event?

the on-toggle callback should not be called for expanded nodes on tree first creation - by design. If you set the value of the expandedNodes property, you know what are the expanded nodes and can do whatever logic is needed. Calling node-toggle on each of those expanded nodes is misleading as they where not clicked and not toggled.

**Comment by andrius-kulbis** [comment]
Every tree node is loaded via ajax, so I dont have all the data available and my nodes are not expanded, because they are still not in the tree.

**Comment by yoavaa** [comment]
Hi Andrius,

I am not sure I understand what you are trying to do. Can you explain the
exact flow of how you use the tree control?
e.g.

1. create the tree control using angular template
2. set tree-data
3. set expanded-nodes
4. load additional nodes via ajax
5. on the callback, updates the tree-data
6. then update the expanded-nodes

Is this what you are doing?

**Comment by andrius-kulbis** [comment]
Yes, almost. At first I have 5 root nodes loaded. On node toggle I load child nodes via AJAX and also save expanded nodes in localStorage. 

On page refresh I load 5 root nodes and then get the expandedNodes from localStorage and update expandedNodes of tree. The nodes are not expanded, because they aRe still not in the tree ( not loaded via ajax). The root node icon changes to "expanded" but child nodes are not loaded, because expandedNodes does not call on-toggle callback.

If this is not clear I will try to create a fiddle with example.

**Comment by yoavaa** [comment]
I see your case. I think that on page refresh you need to implement the logic that iterates the expandedNodes you stored in local storage and fire the ajax logic to load the tree nodes. The tree itself cannot manage this process because that will require the tree to know the ajax flow and manage the sequencing of data loading.

e.g.
imaging the tree
```
node 1
+-- node 2
  +-- node 3
  +-- node 4
node 5
+-- node 6
  +-- node 7
  +-- node 8
```

if node 1 and node 2 are expanded, the sequence of loading nodes via mouse clicks is as follows
a. node 1 is clicked
b. on toggle fired
c. ajax call happens, returns node 2
d. node 2 is added to the tree
e. node 2 is clicked
f. on toggle on node 2 is fired
g. ajax call happens to load children of node 2
h. the resulting nodes are added to the tree

Note the sequence of ajax is that the ajax for clicking node 2 only happens after the ajax for node 1 is completed and node 2 was added to the tree. This sequencing is something you will have to manage and the tree control cannot do so for you because it does not manage the ajax calls.

I suggest you create another ajax method that gets the list of nodes from the local storage and returns the full expanded tree, which you set as the tree data and only then set the tree expanded nodes.
