### ISSUE TITLE
on-selection by double click

### ISSUE THREAD

**Issue by calamarico** [wix/angular-tree-control#274]
Hi!

With the on-selection attribute a callback is fired when a node element is clicked. But, there is a way to instead of a simple click, fires a callback with a double click?

PD: I have a solution, using ng-dbclick passing $event and use $event.target... but my question is if inside the lib there is an easy way.

Thanks!

**Comment by manojvignesh** [comment]
Check this [Link in documentation](http://wix.github.io/angular-tree-control/#externalTemplate).

`<div class="tree-label {{options.labelClass}}" ng-class="[selectedClass(), unselectableClass()]"
                      ng-click="selectNodeLabel(node)" tree-transclude></div>`

You'll find the above code if you use a custom template.
There instead of `ng-click="selectNodeLabel(node)"` use `ng-dbclick="selectNodeLabel(node)"`.

**Comment by calamarico** [comment]
thanks manojvignesh
