### ISSUE TITLE
Is it possible to have an empty folder?

### ISSUE THREAD

**Issue by idreeshaddad** [wix/angular-tree-control#53]
Is it possible to have an empty folder?

**Comment by mitchkeith145** [comment]
I would like to be able to create an empty folder. And when I try to expand that empty folder, I would like no children to appear. I have tried a few different things and can't seem to get it to behave in the way I would expect. If I define a node like this:

> { "name": "folder1", "children": [], "opts": { "isLeaf": false } }

Then when it renders on the page, it shows that "folder1" is a file because the set of children is empty.
If I do something like this: 
> { "name": "folder1", "children": [{}], "opts": { "isLeaf": false } }

Then when it renders on the page, it correctly shows folder1 as an actual folder. However, when folder1 is expanded, it shows that there is one child with an empty data set, because the set of children technically isn't empty. So basically, I am struggling to create a folder node without supplying a non-empty set. And when you supply a non-empty set, if you expand it, it shows that there are contents.

**Comment by yoavaa** [comment]
You can use the isLeaf method
http://wix.github.io/angular-tree-control/#isleaf
