### ISSUE TITLE
Impossible to expand a node when its child have same attributes

### ISSUE THREAD

**Issue by oslo10e** [wix/angular-tree-control#98]
try this example :

HTML
```html
<treecontrol class="tree-classic" tree-model="treedata" node-children="children">
    {{node.name}}
</treecontrol>
```
JS
```javascript
$scope.treedata = [
    {name: 'parent',
     children: [{
         name: 'parent',
         children: [{
             name: 'child'
         }]
     }]
    }
];
```

See also : http://jsfiddle.net/opeaucelle/zdp34dmk/

**Comment by yoavaa** [comment]
This is by design.
The tree control is using node compare method to check between nodes. The default method looks at the node values, and if two nodes have the same properties, from the tree point of view those are the same nodes. 

The solution? use a custom equality function.
http://wix.github.io/angular-tree-control/#equality

**Comment by Julan76** [comment]
Hello,
Try this example please.
http://jsfiddle.net/JsmartGilles/zdp34dmk/9/

I have already tried ( as in the fiddle ):
equality: function(node1, node2) {
return node1 === node2;
}
It's not working.
How can I solve this bug ?
